### ISSUE TITLE
Name Length Limit

### ISSUE THREAD

**Issue by aadiola** [sycasec/janky-leaderboard#3]
An **input limit** of 4 is unusual. I understand this was needed for pretty printing, but for future uses, I think it's best to accept the entire name and store it as well, so that users will not get confused as to why there is a name length limit.

What can be done instead is in the printing part, print the first four chars in the name of the name and three dots (...)[to indicate a cut off part], for a total printing length of 7. Tas, for names less than 7 chars (e.g. 'Rai'), print spaces to ensure alignment of the other columns.

It's also nice to add right-side alignment for the ranking number, since we just rushed it.

**Comment by sycasec** [comment]
added all of these! also added some borders lmao
